# Generated by Django 6.0.3 on 2026-03-22 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchwallpost',
            name='category',
            field=models.CharField(choices=[('looking_for_cofounder', 'Looking for Co-founder'), ('seeking_team', 'Seeking Team Members'), ('idea_validation', 'Idea Validation'), ('seeking_investor', 'Seeking Investor'), ('looking_for_mentor', 'Looking for Mentor'), ('collaboration', 'Collaboration Opportunity'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='pitchwallpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pitches/'),
        ),
        migrations.AddField(
            model_name='pitchwallpost',
            name='interest_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pitchwallpost',
            name='skills_needed',
            field=models.CharField(blank=True, help_text='Comma-separated skills needed', max_length=500),
        ),
        migrations.AddField(
            model_name='pitchwallpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PitchComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.pitchwallpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PitchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='core.pitchwallpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pitch', 'user')},
            },
        ),
    ]
